### ISSUE TITLE
Why did I get a NoSuchMethodError?

### ISSUE THREAD

**Issue by DustinMaple** [ppiastucki/recast4j#109] opened 2021-04-29 13:21 UTC
An error:
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

My version is JDK8u251

**Comment by ppiastucki** [comment] 2021-04-29 13:45
Most likely because of this: https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip
Please try version 1.4.5 and let me know if the issue is fixed.

**Comment by ppiastucki** [comment] 2021-05-10 13:05
I believe the issue is fixed in versions 1.4.4+

**Closed by ppiastucki** 2021-05-10 13:05 UTC
